---
title: "Spotify Data Analysis and Descriptive Statistics"
output: html_notebook
author: CS Duals
date: November 18, 2020
---


```{r}
options(repr.matrix.max.rows=100, repr.matrix.max.cols=20)
```


Import all Libraries
```{r}
# Libraries
options(warn=-1)
library(ggplot2)
library(dplyr)
library(plotly)
library(hrbrthemes)
library(forecast)
library(xts)
library(Metrics)
library(psych)
library(dygraphs)
library(GGally)
library(tidyverse)
library(tidyquant)  
library(cranlogs)   
library(corrr)      
library(cowplot)
library(readr)
library(plyr)
library(formattable)
library(wordcloud)
library(RWeka)
library(qdap)
library(tm)
library(dplyr)
library(magrittr)
library(corrplot)
library(treemap)
library(viridisLite)
library(factoextra)
library(gridExtra)
library(kableExtra)
```


```{r}
#Import Data into DF
df = read.csv(file='./data/data.csv')
df_genre = read.csv(file='./data/data_by_genres.csv')
df_artist = read.csv(file='./data/data_by_artist.csv')
df_year = read.csv(file='./data/data_by_year.csv')
df_genres2 = read.csv(file='./data/data_w_genres.csv')
```


```{r}
# Preview DF
head(df)
head(df_genre)
head(df_artist)
head(df_year)
head(df_genres2)

```

```{r}
# Find certain songs by feature and listen to them
df %>% arrange(desc(acousticness))
df %>% arrange(desc(danceability))
df %>% arrange(desc(valence))
```



Data Cleaning
```{r}
# Take only unique rows - remove duplicates
df <- distinct(df)

# Remove null rows in R
df <- df[rowSums(is.na(df)) == 0,]

# Change year column to a date value
df$year <- as.Date(ISOdate(df$year, 1, 1))
```


Data Summary
```{r}
# Get summary of main dataframe

# Data Dimensions
dim(df)
# Statistical summary of every column
summary(df)
# Print all column names
colnames(df)


# Column names, column types, preview of data
str(df)
```

```{r}
top_artists <- df %>%
    group_by(artists) %>%
    dplyr::summarise(n_apperance = n()) 
top_artists
```




Plot distributions of all values














Try to determine explanations for the top 10% of songs






Use K-Means to determine how many songs are similar


```{r}

```




Correlation Plot of numeric Features
```{r}
# Nice visualization of correlations
numerics = df[,!(colnames(df)  %in% c("id","year","artists","name","release_date"))]
tidyverse_static_correlations <- numerics %>% correlate() 
print.data.frame(tidyverse_static_correlations)

```



5-year rolling correlation of each numeric factor over time

```{r}
# Group by year and get mean of numeric features for each year
df_grped_year <- aggregate(df[,c(names(numerics),"year")], list(df$year), mean)
df_grped_year <- df_grped_year[,!names(df_grped_year) %in% "Group.1"]
df_grped_year
```
```{r}

static_corr_Year <-  df_grped_year[,!names(df_grped_year) %in% "year"] %>% correlate() 
print.data.frame(static_corr_Year)
```


```{r}
# Get rolling correlations
tidyverse_rolling_corr <- df_grped_year %>%
    # Data wrangling
    select(year, energy, popularity) %>%
    # Mutation
    tq_mutate_xy(
        x          = energy,
        y          = popularity,
        mutate_fun = runCor, 
        n          = 10,
        use        = "pairwise.complete.obs",
        col_rename = "rolling_corr"
    )
tidyverse_rolling_corr
```
```{r}
# Join static correlations with rolling correlations
static_corr_pop <- static_corr_Year %>% select(rowname, popularity) %>% rename(feature = rowname)
static_corr_pop
tidyverse_rolling_corr <- tidyverse_rolling_corr %>%
    left_join(static_corr_pop, by = "feature") %>%
    rename(static_corr = all_cran)
tidyverse_rolling_corr
```

```{r}
# Plot
tidyverse_rolling_corr %>%
    ggplot(aes(x = year, color="energy")) +
    # Data
    geom_point(aes(y = rolling_corr), alpha = 0.5) +
    # Aesthetics
    scale_color_tq() +
    labs(
        title = "Rolling Correlations between Popularity and Energy",
        x = "Year", y = "Correlation"
    ) +
    theme_tq() +
    theme(legend.position="none")

```


```{r}
#Time-Series Analysis
#duration_ts <- ts(df_year$duration_ms,start=df_year$year)
colnames(df_year)
subset_year <- df_year[,!(colnames(df_year)  %in% c("key", "mode", "duration_ms"))]

dygraph(subset_year, main = "Song Features Over Time") %>%
  dySeries("tempo", axis = 'y2', label='Tempo') %>%
  dySeries("popularity", axis = 'y2', label='Popularity') %>%
  dySeries("loudness", axis = 'y2', label='loudness') %>%
  dyCSS("legend.css")
```
